version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: openjdk8
    commands:
  pre_build:
    commands:
      - echo ///////////////// Ready to push the image to ECR on `date` /////////////////
      - aws --version
      - docker --version
      - java -version
      - java -version
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - REPOSITORY_URI=549110186018.dkr.ecr.ap-northeast-1.amazonaws.com/parallel-api
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo ///////////////// Building docker image on `date` ///////////////// 
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:lastest
  post_build:
    commands:
      - echo echo ///////////////// Pushing docker image on `date` /////////////////
      - docker push $REPOSITORY_URI:lastest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo "[{\"name\":\"${IMAGE_NAME}\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\"}]" > imagedefinitions.json
artifacts:
    files: 
      - imagedefinitions.json